# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

theme: minimal
day_night: false
font: minimal 
font_size: m

# SEO

site_type: Organization
local_business_type: ''
org_name: ''
description: My research group description.
twitter: ''

# Contact (edit or remove options as required)

email: wenjie.zhang@unsw.edu.au
phone: (+61 2) 93857799
address:
  street: High St, Kensington
  city: Sydney
  region: NSW
  postcode: '2032'
  country: Australia
  country_code: AU
coordinates:
  latitude: '-33.9188012'
  longitude: '151.2308261'
directions: K17, 502
office_hours:
  - 'Monday-Friday 10:00 to 17:00'

appointment_url: 'https://www.cse.unsw.edu.au/~zhangw/'
contact_links:
#  - icon: comments
#    icon_pack: fas
#    name: Discuss on Forum
#    link: 'https://discourse.gohugo.io'

# Site header

main_menu:
  enable: true
  align: r
  show_logo: true
  show_language: false
  show_day_night: true
  show_search: false
  highlight_active_link: false

# Localization

date_format: 'Jan102, 2022'
time_format: '3:04 PM'
address_format: en-us

# Site features

highlight: false
math: false
diagram: false
privacy_pack: false
show_related:
  post: true
  project: true
  publication: true
  talk: true
reading_time: true
section_pager: false
sharing: true
copyright_license:
  enable: false
  allow_derivatives: false
  share_alike: true
  allow_commercial: false
  notice: 'This work is licensed under {license}'
plugins_js: []
avatar:
  gravatar: false
  shape: circle
publications:
  date_format: January 2006
  citation_style: apa
projects:
  post_view: 2
  publication_view: 2
  talk_view: 2
comments:
  provider: ''
  commentable:
    page: true
    post: true
    docs: true
    project: true
    publication: true
    talk: true
  disqus:
    shortname: ''
    show_count: true
  commento:
    url: ''
# search:
#   provider: wowchemy
#   algolia:
#     app_id: ''
#     api_key: ''
#     index_name: ''
#     show_logo: false
map:
  provider: mapnik
  api_key: ''
  zoom: 15
marketing:
  google_analytics: ''
  google_tag_manager: ''
  google_site_verification: ''
  baidu_site_verification: ''
  baidu_tongji: ''
cms:
  branch: main
  local_backend: false
icon:
  pack:
    ai: true
